### ISSUE TITLE
Exception with html tags in query.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#11]
Hi Tim,

I was working on html tags handling in text. During testing found an issue with a query which has html tags in it. A query with html tags are not usual but just thought of sharing the exception.

Query : `term<sub>2</sub>`
Exception:
`org.apache.lucene.queryparser.classic.ParseException: Didn't find matching: /
	at org.apache.lucene.queryparser.spans.SpanQueryLexer.readToMatchingEndToken(SpanQueryLexer.java:646)
	at org.apache.lucene.queryparser.spans.SpanQueryLexer.nextToken(SpanQueryLexer.java:165)
	at org.apache.lucene.queryparser.spans.SpanQueryLexer.getTokens(SpanQueryLexer.java:102)
	at org.apache.lucene.queryparser.spans.SpanQueryParser._parse(SpanQueryParser.java:232)
	at org.apache.lucene.queryparser.spans.SpanQueryParser.parse(SpanQueryParser.java:222)`

Thanks,
Modassar

**Comment by tballison** [comment]
Y, that's expected behavior.  When it hits the '/', it thinks it has hit the start of a regex, and it is looking for the closing '/'.  If you are literally looking for a single token 'term<sub>2</sub>', then you should be able to escape via single quotes or backslash.

**Comment by tballison** [comment]
Mind if we close this?  HTML markup is not part of the design spec.
